"""Add schedule_events time-order check and index

Revision ID: af88e69ec11d
Revises: 60923cbdd9bd
Create Date: 2025-08-17 00:46:48.279019+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af88e69ec11d'
down_revision: Union[str, Sequence[str], None] = '60923cbdd9bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_schedule_events_task_start', 'schedule_events', ['task_id', 'start_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_schedule_events_task_start', table_name='schedule_events')
    # ### end Alembic commands ###
